### ISSUE TITLE
[Bug] Use correct decimal scale for function `round`

### ISSUE THREAD

**Issue by Gabriel39** [apache/doris#15307] opened 2022-12-22 14:47 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

As discussed in #14946, round(16.025000, 2) should be 16.03 instead of 16.030000 if 16.025000 is a DECIMALV3 type.

Related functions:
`round`
`floor`
`ceil`
`truncate`
`round_bankers`

### What You Expected?

1

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by maochongxin** [comment] 2022-12-22 15:20
I willing to continue working on this issue

**Comment by Gabriel39** [comment] 2022-12-23 01:59
> I willing to continue working on this issue

Great!

**Comment by maochongxin** [comment] 2022-12-27 18:15
version `849adca`, my test results are like below
```
MySQL [(none)]> show frontends;
+-------------------------------+------------+-------------+----------+-----------+---------+----------+----------+------------+------+-------+-------------------+---------------------+----------+--------+---------------------------+------------------+
| Name                          | IP         | EditLogPort | HttpPort | QueryPort | RpcPort | Role     | IsMaster | ClusterId  | Join | Alive | ReplayedJournalId | LastHeartbeat       | IsHelper | ErrMsg | Version                   | CurrentConnected |
+-------------------------------+------------+-------------+----------+-----------+---------+----------+----------+------------+------+-------+-------------------+---------------------+----------+--------+---------------------------+------------------+
| 172.17.0.2_9010_1672159914240 | 172.17.0.2 | 9010        | 8030     | 9030      | 9020    | FOLLOWER | true     | 1372269922 | true | true  | 1336              | 2022-12-27 18:05:32 | true     |        | doris-0.0.0-trunk-849adca | Yes              |
+-------------------------------+------------+-------------+----------+-----------+---------+----------+----------+------------+------+-------+-------------------+---------------------+----------+--------+---------------------------+------------------+
1 row in set (0.08 sec)

MySQL [(none)]> select round(16.025000, 2);
+------------------+
| round(16.025, 2) |
+------------------+
|            16.02 |
+------------------+
1 row in set (0.27 sec)

MySQL [(none)]>
```

**Comment by Gabriel39** [comment] 2022-12-28 02:33
> m with the rounding result, and the precision problem seems to have been fix

Currently, literal 16.025000 is considered as DECIMALV2 by default so we got a wrong result. To test DECIMALV3, you should:
1. CREATE TABLE with a DECIMALV3 column `col`
2. INSERT data INTO this table (e.g. 16.025000)
3. select round(`col`, 2) from this table;

**Comment by Prakhar047** [comment] 2023-01-09 07:34
@Gabriel39 , I want to work on this issue. Can you please assign to me?

**Comment by Gabriel39** [comment] 2023-01-10 02:23
> @Gabriel39 , I want to work on this issue. Can you please assign to me?

Hi @Prakhar047 , actually, I'm not sure the progress which is done by @maochongxin . @maochongxin Have you done this job ?

**Comment by maochongxin** [comment] 2023-01-10 02:34
> > @Gabriel39 , I want to work on this issue. Can you please assign to me?
> 
> Hi @Prakhar047 , actually, I'm not sure the progress which is done by @maochongxin . @maochongxin Have you done this job ?

I'm sorry for the long absence of updates due to illness, can assign to @Prakhar047 , thanks

**Comment by Prakhar047** [comment] 2023-01-10 07:25
@Gabriel39 Can you please guide me how to start?

**Comment by Yukang-Lian** [comment] 2023-01-10 08:26
1. Compile and run the master branch of doris to reproduce the above bug.
2. The implementation of the `round` function is located in `be/src/vec/functions/round.h`, try to understand it.
3. Find bugs step by step through logical analysis and solve it.
4. Add be test and regression test.
5. Submit your first PR.

maybe @Gabriel39 will also add more specific steps. If you have any question, I am willing to help.! Good luck :)

**Comment by Gabriel39** [comment] 2023-01-11 02:26
@Yukang-Lian Thanks for your kindly help! I think these steps are specific enough. @Prakhar047 Follow these steps and feel free to discuss with me if you need help.

**Comment by Prakhar047** [comment] 2023-01-13 12:29
Thank You @Gabriel39 & @Yukang-Lian for you help. I'm new to Apache doris repository can you guide me how to set up the environment.

**Comment by Yukang-Lian** [comment] 2023-01-13 12:34
You can follow this [link](https://doris.incubator.apache.org/zh-CN/docs/dev/install/source-install/compilation) to set up environment and compile doris.

**Comment by Yukang-Lian** [comment] 2023-01-13 12:38
You are welcome.

**Comment by Mint-Boy-He** [comment] 2023-01-18 05:46
I have encountered the same problem with version 1.2.1, but version 1.2.0 is normal.
（在1.2.1版本中遇到相同问题，在1.2.0中没问题）

I found that it may be related to the odd and even number of digits to be reserved. That is, version 1.2.1. If the second decimal digit reserved is an even number, it will be discarded; If it is odd, the normal function is rounding
（我发现可能跟要保留的第几位数的奇偶数有关。即1.2.1版本，如果保留的第二位小数是偶数，则舍弃；如果是奇数则正常功能即四舍五入）
![图片](https://user-images.githubusercontent.com/65714358/213093908-d062e533-e6a6-4755-9170-ea7bc9cccedf.png)
Test SQL

**Comment by Gabriel39** [comment] 2023-02-09 08:51
> I have encountered the same problem with version 1.2.1, but version 1.2.0 is normal. （在1.2.1版本中遇到相同问题，在1.2.0中没问题）
> 
> I found that it may be related to the odd and even number of digits to be reserved. That is, version 1.2.1. If the second decimal digit reserved is an even number, it will be discarded; If it is odd, the normal function is rounding （我发现可能跟要保留的第几位数的奇偶数有关。即1.2.1版本，如果保留的第二位小数是偶数，则舍弃；如果是奇数则正常功能即四舍五入） ![图片](https://user-images.githubusercontent.com/65714358/213093908-d062e533-e6a6-4755-9170-ea7bc9cccedf.png) select round(46.215,2), round(46.225,2), round(46.235,2), round(46.245,2), round(46.255,2), round(46.265,2), round(46.275,2), round(46.285,2), round(46.295,2)\G;

Hi @Mint-Boy-He , actually, function `round` doesn't have a reasonable behavior before. This is because DECIMAL type in Doris is not a real decimal so we cannot provide a precise value after `found`. Fortunately we have DECIMALV3 since 1.2.1 which can provide a precise value for functions like `round`. So you can just use DECIMALV3 if you need a precise rounded value.

For example,
1. CREATE TABLE `decimal_table` (`col` DECIMALV3(10, 4) NOT NULL COMMENT ''     ) distributed by hash(`col`) buckets 1      properties("replication_num"="1");
2. insert into decimal_table values (46.215), (46.225), (46.235), (46.245);
3. select col, round(col, 2) from decimal_table;

And then we got results below:
![image](https://user-images.githubusercontent.com/37700562/217762638-7199fd0f-ba42-4f30-83b7-08e332220c5b.png)

If you have any problem using DECIMALV3, feel free to tell me and I'm glad to offer your help

**Comment by Gabriel39** [comment] 2023-02-09 08:55
Hi @Prakhar047 , we need this improvement in 2.0 and since time is limited, I decided to assign this issue to @maochongxin again. Sorry for that. If you are interested in Doris and need a good-first-issue, please tell me and I will find another issue for you.

**Closed** 2023-03-01 04:28 UTC
Labels: good first issue
