### ISSUE TITLE
[Bug] get different result between 2.0 and 2.1 when select has COALESCE, min_by, max_by,GROUPING SETS

### ISSUE THREAD

**Issue by nextdreamblue** [apache/doris#40506] opened 2024-09-07 05:23 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0/2.1

### What's Wrong?

```
CREATE TABLE `test9992` (
    `ddate` date NULL,
    `time` datetime NULL,
    `id` varchar(100) NULL,
    `id1` varchar(100) NULL,
    `id2` varchar(100) NULL,
    `id3` varchar(100) NULL,
    `id4` varchar(100) NULL,
    `id5` varchar(100) NULL,
    `wrong` varchar(100) NULL,
    `zone` varchar(100) NULL
) ENGINE = OLAP DUPLICATE KEY(`ddate`) DISTRIBUTED BY HASH(`ddate`) BUCKETS 1 PROPERTIES (
    "replication_allocation" = "tag.location.default: 3"
);

insert into
    test9992
values
(
        '2024-06-27',
        '2024-06-27 00:00:00',
        '100',
        'xxxx',
        '4',
        '',
        '123',
        'zzz',
        'ABC',
        'UTC+8'
    );

SELECT
    ddate,
    id,
    id1,
    COALESCE(id2, '99999') AS id2,
    COALESCE(id4, '99999') AS id4,
    COALESCE(id5, '99999') AS id5,
    COALESCE(wrong, '99999') AS wrong,
    id3,
    min_by(wrong, time) AS aaa,
    max_by(wrong, time) AS bbb,
    zone
FROM
    (
        SELECT
            ddate,
            time,
            id,
            id1,
            id2,
            id3,
            id4,
            id5,
            wrong,
            zone
        FROM
            test9992
        WHERE
            ddate >= '2024-06-27'
            AND ddate < '2024-06-28'
            AND zone IN (
                'UTC+8',
                'UTC+9',
                'UTC+10'
            )
    ) a
GROUP BY
    GROUPING SETS (
        (
            ddate,
            id,
            id1,
            id3,
            zone,
            id2,
            id4,
            id5,
            a.wrong
        ),
        (
            ddate,
            id,
            id1,
            id3,
            zone,
            id2,
            id4,
            id5
        )
    );

```

will get different result between 2.0 and 2.1

2.0 will get
```
+------------+------+------+------+------+------+-------+------+--------------------+-------------------+-------+
| ddate      | id   | id1  | id2  | id4  | id5  | wrong | id3  | aaa              | bbb                 | zone  |
+------------+------+------+------+------+------+-------+------+--------------------+-------------------+-------+
| 2024-06-27 | 100  | xxxx | 4    | 123  | zzz  | ABC   |      | ABC                | ABC               | UTC+8 |
| 2024-06-27 | 100  | xxxx | 4    | 123  | zzz  | 99999 |      | NULL               | NULL              | UTC+8 |
+------------+------+------+------+------+------+-------+------+--------------------+-------------------+-------+
```
2.1 will get 
```
+------------+------+------+------+------+------+-------+------+--------------------+-------------------+-------+
| ddate      | id   | id1  | id2  | id4  | id5  | wrong | id3  | aaa              | bbb                 | zone  |
+------------+------+------+------+------+------+-------+------+--------------------+-------------------+-------+
| 2024-06-27 | 100  | xxxx | 4    | 123  | zzz  | ABC   |      | ABC                | ABC               | UTC+8 |
| 2024-06-27 | 100  | xxxx | 4    | 123  | zzz  | 99999 |      | ABC                | ABC               | UTC+8 |
+------------+------+------+------+------+------+-------+------+--------------------+-------------------+-------+
```
if set enable_nereids_planner = false on 2.0 and 2.1 
will get 
```
+------------+------+------+------+------+------+-------+------+--------------------+-------------------+-------+
| ddate      | id   | id1  | id2  | id4  | id5  | wrong | id3  | aaa              | bbb                 | zone  |
+------------+------+------+------+------+------+-------+------+--------------------+-------------------+-------+
| 2024-06-27 | 100  | xxxx | 4    | 123  | zzz  | ABC   |      | ABC                | ABC               | UTC+8 |
| 2024-06-27 | 100  | xxxx | 4    | 123  | zzz  | 99999 |      | NULL               | NULL              | UTC+8 |
+------------+------+------+------+------+------+-------+------+--------------------+-------------------+-------+
```
### What You Expected?

which result is right?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Mryange** [comment] 2024-09-09 03:10
This is because on version 2.0, nereids_planner has fallen back to the old optimizer. You can reproduce the error by executing:
```
set enable_nereids_planner=true;
set enable_fallback_to_original_planner=false;
```
This will result in the following error:
```
ERROR 1105 (HY000): errCode = 2, detailMessage = Unexpected exception: column: wrong cannot both in select list and aggregate functions when using GROUPING SETS/CUBE/ROLLUP, please use union instead.
```
This issue occurs because https://github.com/apache/doris/pull/31318 has not been merged into the 2.0 branch.

**Closed** 2024-09-11 06:05 UTC
