### ISSUE TITLE
[Bug] The execution of multi_search_all_positions(x, null) leads to a BE crash

### ISSUE THREAD

**Issue by yoursweetie** [apache/doris#32272] opened 2024-03-15 01:54 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-2.0.5-rc01-204fde9

### What's Wrong?

The execution of multi_search_all_positions(x, null) leads to a BE crash
![图片](https://github.com/apache/doris/assets/52481734/5bbcafa2-bf7c-46bd-9273-df3970155f07)

### What You Expected?

BE does not crash but throws an exception

### How to Reproduce?

`create table tb0(char_3 char(3)) DISTRIBUTED BY HASH (char_3) buckets auto PROPERTIES ( "replication_num" = "1" );`

`insert into tb0 values('aaa');`

`select multi_search_all_positions(char_3, null) from tb0;`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wyxxxcat** [comment] 2024-03-16 09:36
I cannot reproduce it and use version master
![Uploading 截图 2024-03-15 11-20-51.png…]()

**Comment by wyxxxcat** [comment] 2024-03-16 09:38
I cannot reproduce it and use version master
![截图 2024-03-16 17-35-25.png](https://img2.imgtp.com/2024/03/16/TpM0NsAO.png)

**Comment by yoursweetie** [comment] 2024-03-18 03:50
> I cannot reproduce it and use version master ![截图 2024-03-16 17-35-25.png](https://camo.githubusercontent.com/dc62cc4a5368e9192674a41ad2ae9d9f1400caaed30d0d46d82c0cc4de69ad64/68747470733a2f2f696d67322e696d6774702e636f6d2f323032342f30332f31362f54704d304e73414f2e706e67)

Remove "master" from affected versions, but version 2.0.5-rc01-204fde9 is indeed affected.

**Comment by cambyzju** [comment] 2024-03-18 11:30
fixed by: https://github.com/apache/doris/pull/31312

**Closed** 2024-03-19 02:58 UTC
