### ISSUE TITLE
[Bug] transport: Error while dialing: dial tcp 0.0.0.0:9090

### ISSUE THREAD

**Issue by zhaopinglu** [apache/doris#36340] opened 2024-06-15 07:25 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris v 2.1.3

python package:
adbc-driver-flightsql     1.0.0
pydoris                   1.0.5.3
pydoris-client            1.0.4

### What's Wrong?

OperationalError: IO: [FlightSQL] connection error: desc = "transport: Error while dialing: dial tcp 0.0.0.0:9090: connectex: No connection could be made because the target machine actively refused it." (Unavailable; DoGet: endpoint 0: [uri:"grpc+tcp://0.0.0.0:9090"])

possible related issue:

[fix](arrow-flight-sql) Fix Arrow Flight bind wrong Host in Fqdn #34850

'### What You Expected?

'## 1

'##################
 dbapi_adbc_execute_fetchallarrow, cost:0:00:00.033296, bytes:101, len(arrow_data):6
'## 2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 1 columns):
 '#   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Database  6 non-null      object
dtypes: object(1)
memory usage: 547.0 bytes
None
'## 3
              Database
0    __internal_schema
1     arrow_flight_sql
2   information_schema
3                mysql
4  pydoris_client_test

### How to Reproduce?

Run python script remotely (not in the same vm as doris be'):

```
import adbc_driver_manager
import adbc_driver_flightsql.dbapi as flight_sql
import pandas
from datetime import datetime
#import pyarrow as pa
#import pyarrow.flight as fl


conn = flight_sql.connect(uri="grpc://x.x.x.x:9090", db_kwargs={
            adbc_driver_manager.DatabaseOptions.USERNAME.value: "root",
            adbc_driver_manager.DatabaseOptions.PASSWORD.value: ""
        },
        autocommit=False
)
cursor = conn.cursor()

#cursor.execute("DROP DATABASE IF EXISTS arrow_flight_sql FORCE;")
#cursor.execute("select now();")
cursor.execute("show databases;")

start_time = datetime.now()
arrow_data = cursor.fetchallarrow()
dataframe = arrow_data.to_pandas()

print("## 1")
print("\n##################\n dbapi_adbc_execute_fetchallarrow" +
      ", cost:" + str(datetime.now() - start_time) +
      ", bytes:" + str(arrow_data.nbytes) +
      ", len(arrow_data):" + str(len(arrow_data))
)
print("## 2")
print(dataframe.info(memory_usage='deep'))
print("## 3")
print(dataframe)
```

### Anything Else?
The tcp packets captured by wireshark show:
The doris be server return 'grpc+tcp://0.0.0.0:9090' to client. This could be the reason why client is trying to connect the endpoint: 0.0.0.0:9090

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by drreddy** [comment] 2024-06-22 09:57
Hi,
+1 I'm also facing the same issue, were you able to figure out what the problem is / fix is ?

**Comment by xinyiZzz** [comment] 2024-06-24 11:25
Hi @zhaopinglu @drreddy 
1. check Doris BE version and upgrade it to 2.1.3-rc08 or above, in 2.1.3-rc08 fix #34850.
2. use FE host to connect, `//host:9090`
3. show the results of `show frontends;` and `show backends;`
4. do you use fqdn?

**Comment by drreddy** [comment] 2024-07-02 10:59
Hi @xinyiZzz 

We've upgraded our cluster to doris-2.1.4-rc03-e93678fd1e and retried the same, we are still facing the same issue. We are not using fqdn anywhere.

**Comment by xinyiZzz** [comment] 2024-07-03 05:21
> Hi @xinyiZzz
> 
> We've upgraded our cluster to doris-2.1.4-rc03-e93678fd1e and retried the same, we are still facing the same issue. We are not using fqdn anywhere.

If you could provide the following information, It would be helpful to analyze this issue.
1. `show frontends;` execution results
2. `show backends;` execution results
3. `fe.log` partial log of query from start to end.
4. `be.INFO` partial log of query from start to end.

**Comment by drreddy** [comment] 2024-07-03 06:27
Hi @xinyiZzz 

PFB the responses for the queries:

1. show frontends output:
`
mysql> show frontends\G
*************************** 1. row ***************************
              Name: fe_584773d2_b483_446a_bad8_040765483c48
              Host: 10.0.2.4
       EditLogPort: 9010
          HttpPort: 8030
         QueryPort: 9030
           RpcPort: 9020
ArrowFlightSqlPort: 9090
              Role: FOLLOWER
          IsMaster: true
         ClusterId: 339655541
              Join: true
             Alive: true
 ReplayedJournalId: 169718
     LastStartTime: 2024-07-02 10:46:27
     LastHeartbeat: 2024-07-03 06:21:23
          IsHelper: true
            ErrMsg:
           Version: doris-2.1.4-rc03-e93678fd1e
  CurrentConnected: Yes
`

2. Show backends output
`
mysql> show backends\G
*************************** 1. row ***************************
              BackendId: 13058
                   Host: 10.0.2.5
          HeartbeatPort: 9050
                 BePort: 9060
               HttpPort: 8040
               BrpcPort: 8060
     ArrowFlightSqlPort: 9091
          LastStartTime: 2024-07-02 10:46:58
          LastHeartbeat: 2024-07-03 06:21:13
                  Alive: true
   SystemDecommissioned: false
              TabletNum: 3645
       DataUsedCapacity: 789.687 MB
      TrashUsedCapacity: 1.845 GB
          AvailCapacity: 124.288 GB
          TotalCapacity: 127.936 GB
                UsedPct: 2.85 %
         MaxDiskUsedPct: 2.85 %
     RemoteUsedCapacity: 0.000
                    Tag: {"location" : "default"}
                 ErrMsg:
                Version: doris-2.1.4-rc03-e93678fd1e
                 Status: {"lastSuccessReportTabletsTime":"2024-07-03 06:21:08","lastStreamLoadTime":-1,"isQueryDisabled":false,"isLoadDisabled":false}
HeartbeatFailureCounter: 0
               NodeRole: mix
*************************** 2. row ***************************
              BackendId: 13059
                   Host: 10.0.2.6
          HeartbeatPort: 9050
                 BePort: 9060
               HttpPort: 8040
               BrpcPort: 8060
     ArrowFlightSqlPort: 9091
          LastStartTime: 2024-07-02 10:47:24
          LastHeartbeat: 2024-07-03 06:21:13
                  Alive: true
   SystemDecommissioned: false
              TabletNum: 3779
       DataUsedCapacity: 3.440 GB
      TrashUsedCapacity: 245.602 MB
          AvailCapacity: 123.218 GB
          TotalCapacity: 127.936 GB
                UsedPct: 3.69 %
         MaxDiskUsedPct: 3.69 %
     RemoteUsedCapacity: 0.000
                    Tag: {"location" : "default"}
                 ErrMsg:
                Version: doris-2.1.4-rc03-e93678fd1e
                 Status: {"lastSuccessReportTabletsTime":"2024-07-03 06:20:47","lastStreamLoadTime":-1,"isQueryDisabled":false,"isLoadDisabled":false}
HeartbeatFailureCounter: 0
               NodeRole: mix
*************************** 3. row ***************************
              BackendId: 62290
                   Host: 10.0.2.7
          HeartbeatPort: 9050
                 BePort: 9060
               HttpPort: 8040
               BrpcPort: 8060
     ArrowFlightSqlPort: 9091
          LastStartTime: 2024-07-02 10:47:54
          LastHeartbeat: 2024-07-03 06:21:13
                  Alive: true
   SystemDecommissioned: false
              TabletNum: 3777
       DataUsedCapacity: 3.283 GB
      TrashUsedCapacity: 488.622 MB
          AvailCapacity: 123.146 GB
          TotalCapacity: 127.936 GB
                UsedPct: 3.74 %
         MaxDiskUsedPct: 3.74 %
     RemoteUsedCapacity: 0.000
                    Tag: {"location" : "default"}
                 ErrMsg:
                Version: doris-2.1.4-rc03-e93678fd1e
                 Status: {"lastSuccessReportTabletsTime":"2024-07-03 06:21:03","lastStreamLoadTime":-1,"isQueryDisabled":false,"isLoadDisabled":false}
HeartbeatFailureCounter: 0
               NodeRole: mix
`

w.r.t the logs I'm not sure for which query you want the log for ?? Also I've have never handled doris logs, could you guide me on how to get the specific logs for a query.

**Comment by chengxin1374** [comment] 2024-08-05 07:54
> 2.1.4-rc03

i also use doris-version:2.1.4-rc03.  Have you solved the problem? I have the same problem as you.

**Comment by denniskyleung** [comment] 2024-08-20 04:10
Same issue using doris-2.1.5-rc02. However, the ADBC connection works with doris-2.1.2-rc04 with the same configuration.

**Comment by xinyiZzz** [comment] 2024-08-27 14:31
@denniskyleung @zhaopinglu @chengxin1374 @drreddy 

Fixed in https://github.com/apache/doris/pull/40002, sorry for taking so long.

This problem occurs when query results are returned from FE Arrow Flight server, such as `show tables;`, `show databases;`. no problem when query results are returned from BE Arrow Flight server, such as the normal query statement `select * from xxx`.

**Closed by xinyiZzz** 2024-08-27 14:31 UTC
